#!/usr/bin/env python3
import os
import json
import subprocess
import time
from datetime import datetime

# Paths
WORKSPACE = "/root/.openclaw/workspace"
REPORT_PATH = os.path.join(WORKSPACE, "GOVERNMENT_BY_NUMBERS.md")
HEALTH_SCRIPT = os.path.join(WORKSPACE, "03 Reference/02 System Configs/scripts/daily_health.py")
USAGE_SCRIPT = os.path.join(WORKSPACE, "03 Reference/02 System Configs/scripts/update_dashboard_usage.py")
ROUTING_STATE = os.path.join(WORKSPACE, "state/llm-routing.json")

def get_health():
    try:
        out = subprocess.check_output(f"python3 '{HEALTH_SCRIPT}'", shell=True).decode()
        return json.loads(out)
    except:
        return {"status": "ERROR", "checks": []}

def get_usage():
    try:
        subprocess.run(f"python3 '{USAGE_SCRIPT}'", shell=True, capture_output=True)
        if os.path.exists(ROUTING_STATE):
            with open(ROUTING_STATE, 'r') as f:
                return json.load(f)
        return {}
    except:
        return {}

def generate_report():
    health = get_health()
    usage = get_usage()
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report_lines = [
        "# 📊 Government by Numbers: Daily Report",
        f"**Timestamp:** {now}",
        f"**Overall Status:** {health.get('status', 'UNKNOWN')}",
        "",
        "## 🛡️ Stability (System Health)",
        "| ID | Check Name | Status | Details |",
        "|----|------------|--------|---------|"
    ]

    for check in health.get('checks', []):
        status_emoji = "✅" if check['status'] == "OK" else "⚠️" if check['status'] == "WARN" else "❌"
        report_lines.append(f"| {check['id']} | {check['name']} | {status_emoji} {check['status']} | {check.get('details', '-')} |")

    report_lines.extend([
        "",
        "## 💰 Cost Control (Usage Statistics)"
    ])
    
    if usage:
        claude = usage.get('claude', {})
        codex = usage.get('codex', {})
        routing = usage.get('routing', {})
        
        claude_pct = claude.get('session', {}).get('used_pct', 0) * 100
        report_lines.append(f"- **Cloud Usage (Gemini/Claude):** {claude_pct:.1f}% of daily soft-limit")
        report_lines.append(f"- **Local Worker Usage (Qwen/Codex):** {codex.get('tasks_today', 0)} tasks processed locally")
        report_lines.append(f"- **Efficiency (Routing):** {routing.get('codex_pct', 0)}% of tasks handled by Local AI")
    else:
        report_lines.append("_Usage data unavailable._")

    report_lines.extend([
        "",
        "---",
        "*Report generated by David's Governance Engine.*"
    ])

    report_content = "\n".join(report_lines)
    # Save history
    history_dir = os.path.join(WORKSPACE, "03 Reference/01 Documentation/Government_By_Numbers")
    history_file = os.path.join(history_dir, f"GBN_{datetime.now().strftime('%Y-%m-%d')}.md")
    with open(history_file, 'w') as f:
        f.write(report_content)
    
    with open(REPORT_PATH, 'w') as f:
        f.write(report_content)
    return report_content, history_file

if __name__ == "__main__":
    report_content, history_file = generate_report()
    print(history_file)
