/**
 * Micro-Task 3.3: Data Formatting Logic (Dual Output Strategy)
 * 1. Agent-Friendly (MD/English): For AI long-term memory.
 * 2. Human-Friendly (Burmese): For Nolan's 24h report.
 */

const data = items[0].json; 
const timestamp = new Date().toLocaleString('en-GB', { timeZone: 'Asia/Yangon' });

// --- 1. Agentic Memory Format (English/MD) ---
// Optimized for LLM retrieval and future agent context
const agenticMD = `---
type: daily_distillation
date: ${timestamp}
source: n8n_vps_logs
---
# Memory Distillation: ${timestamp}

## [Preferences]
${data.preferences || "None detected."}

## [Decisions]
${data.decisions || "None recorded."}

## [Errors & Fixes]
${data.errors || "System healthy."}

## [Next Steps]
${data.nextSteps || "Continue monitoring."}
`;

// --- 2. Nolan's Report Format (Burmese/Markdown) ---
// Warm, clear, and personal 2 AM Vibe
const nolanReport = `# 🌟 ယနေ့အတွက် လုပ်ငန်းအနှစ်ချုပ် (${timestamp})

နေကောင်းလား Nolan! ဒီနေ့ VPS ထဲမှာ ဖြစ်ပျက်ခဲ့သမျှကို David က သေချာဖတ်ပြီး အနှစ်ချုပ်ပေးထားပါတယ်။

### 💎 အသစ်သိရှိရသော အကြိုက်များ
${data.preferences || "- ထူးထူးခြားခြား မရှိသေးပါ။"}

### ⚔️ ယနေ့ ချမှတ်ခဲ့သော ဆုံးဖြတ်ချက်များ
${data.decisions || "- အစီအစဉ်အတိုင်းပဲ ဆက်သွားနေပါတယ်။"}

### 🛠️ Error များနှင့် ဖြေရှင်းမှုများ
${data.errors || "- စနစ်တစ်ခုလုံး အဆင်ပြေပြေ လည်ပတ်နေပါတယ်။"}

### 🚀 ရှေ့ဆက်လုပ်ဆောင်ရန်များ
${data.nextSteps || "- သတ်မှတ်ထားတဲ့ workflow အတိုင်း ဆက်သွားပါမယ်။"}

---
*Generated by David (Your 2 AM Friend)*
`;

return [{
    json: {
        agentic_memory: agenticMD,
        nolan_report: nolanReport,
        filename: `report_${new Date().toISOString().split('T')[0]}.md`
    }
}];
